server:
  port: 8080

spring:
  application:
    name: chatbox

#  datasource:
#    url: jdbc:mysql://localhost:3306/greenshield_db?createDatabaseIfNotExist=true
#    username: root
#    password:  root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 20971520
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  gemini:
    api:
      key: AIzaSyB0W8IUauX2ZrZZ6CnkRWlu1w_2pWE5_6E
